name: Build Plugin

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Setup Zulu OpenJDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: '17.0.2'
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Stage artifacts
        run: mkdir staged && cp target/*.jar staged

      - name: Upload staged artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build
          path: staged/